export type IsoCodes = {
  alpha2: string;
  alpha3: string;
  numeric: string;
};

/** ISO 3166-1 for countries in the Fauda snapshot. numeric is zero-padded (matches Natural Earth ids). */
export const ISO_BY_ALPHA2: Record<string, IsoCodes> = {
  IL: { alpha2: "IL", alpha3: "ISR", numeric: "376" },
  LB: { alpha2: "LB", alpha3: "LBN", numeric: "422" },
  JO: { alpha2: "JO", alpha3: "JOR", numeric: "400" },
  AE: { alpha2: "AE", alpha3: "ARE", numeric: "784" },
  BH: { alpha2: "BH", alpha3: "BHR", numeric: "048" },
  QA: { alpha2: "QA", alpha3: "QAT", numeric: "634" },
  OM: { alpha2: "OM", alpha3: "OMN", numeric: "512" },
  KW: { alpha2: "KW", alpha3: "KWT", numeric: "414" },
  EG: { alpha2: "EG", alpha3: "EGY", numeric: "818" },
  MA: { alpha2: "MA", alpha3: "MAR", numeric: "504" },
  SA: { alpha2: "SA", alpha3: "SAU", numeric: "682" },
  TR: { alpha2: "TR", alpha3: "TUR", numeric: "792" },
  FR: { alpha2: "FR", alpha3: "FRA", numeric: "250" },
  DE: { alpha2: "DE", alpha3: "DEU", numeric: "276" },
  NL: { alpha2: "NL", alpha3: "NLD", numeric: "528" },
  IT: { alpha2: "IT", alpha3: "ITA", numeric: "380" },
  GR: { alpha2: "GR", alpha3: "GRC", numeric: "300" },
  CY: { alpha2: "CY", alpha3: "CYP", numeric: "196" },
  RO: { alpha2: "RO", alpha3: "ROU", numeric: "642" },
  CZ: { alpha2: "CZ", alpha3: "CZE", numeric: "203" },
  SK: { alpha2: "SK", alpha3: "SVK", numeric: "703" },
  HU: { alpha2: "HU", alpha3: "HUN", numeric: "348" },
  RS: { alpha2: "RS", alpha3: "SRB", numeric: "688" },
  HR: { alpha2: "HR", alpha3: "HRV", numeric: "191" },
  BG: { alpha2: "BG", alpha3: "BGR", numeric: "100" },
  PL: { alpha2: "PL", alpha3: "POL", numeric: "616" },
  BE: { alpha2: "BE", alpha3: "BEL", numeric: "056" },
  FI: { alpha2: "FI", alpha3: "FIN", numeric: "246" },
  AT: { alpha2: "AT", alpha3: "AUT", numeric: "040" },
  LU: { alpha2: "LU", alpha3: "LUX", numeric: "442" },
  CH: { alpha2: "CH", alpha3: "CHE", numeric: "756" },
  SE: { alpha2: "SE", alpha3: "SWE", numeric: "752" },
  NO: { alpha2: "NO", alpha3: "NOR", numeric: "578" },
  DK: { alpha2: "DK", alpha3: "DNK", numeric: "208" },
  ES: { alpha2: "ES", alpha3: "ESP", numeric: "724" },
  PT: { alpha2: "PT", alpha3: "PRT", numeric: "620" },
  SI: { alpha2: "SI", alpha3: "SVN", numeric: "705" },
  LT: { alpha2: "LT", alpha3: "LTU", numeric: "440" },
  IE: { alpha2: "IE", alpha3: "IRL", numeric: "372" },
  GB: { alpha2: "GB", alpha3: "GBR", numeric: "826" },
  IN: { alpha2: "IN", alpha3: "IND", numeric: "356" },
  LK: { alpha2: "LK", alpha3: "LKA", numeric: "144" },
  PK: { alpha2: "PK", alpha3: "PAK", numeric: "586" },
  BD: { alpha2: "BD", alpha3: "BGD", numeric: "050" },
  KE: { alpha2: "KE", alpha3: "KEN", numeric: "404" },
  NG: { alpha2: "NG", alpha3: "NGA", numeric: "566" },
  AR: { alpha2: "AR", alpha3: "ARG", numeric: "032" },
  BR: { alpha2: "BR", alpha3: "BRA", numeric: "076" },
  CL: { alpha2: "CL", alpha3: "CHL", numeric: "152" },
  PA: { alpha2: "PA", alpha3: "PAN", numeric: "591" },
  US: { alpha2: "US", alpha3: "USA", numeric: "840" },
  LY: { alpha2: "LY", alpha3: "LBY", numeric: "434" },
  PS: { alpha2: "PS", alpha3: "PSE", numeric: "275" },
  CA: { alpha2: "CA", alpha3: "CAN", numeric: "124" },
  AU: { alpha2: "AU", alpha3: "AUS", numeric: "036" },
  NZ: { alpha2: "NZ", alpha3: "NZL", numeric: "554" },
  MX: { alpha2: "MX", alpha3: "MEX", numeric: "484" },
  CO: { alpha2: "CO", alpha3: "COL", numeric: "170" },
  PE: { alpha2: "PE", alpha3: "PER", numeric: "604" },
  JP: { alpha2: "JP", alpha3: "JPN", numeric: "392" },
  KR: { alpha2: "KR", alpha3: "KOR", numeric: "410" },
  PH: { alpha2: "PH", alpha3: "PHL", numeric: "608" },
  TH: { alpha2: "TH", alpha3: "THA", numeric: "764" },
  ID: { alpha2: "ID", alpha3: "IDN", numeric: "360" },
  MY: { alpha2: "MY", alpha3: "MYS", numeric: "458" },
  TN: { alpha2: "TN", alpha3: "TUN", numeric: "788" },
  DZ: { alpha2: "DZ", alpha3: "DZA", numeric: "012" },
  IQ: { alpha2: "IQ", alpha3: "IRQ", numeric: "368" },
  SY: { alpha2: "SY", alpha3: "SYR", numeric: "760" },
  IR: { alpha2: "IR", alpha3: "IRN", numeric: "364" },
  ZA: { alpha2: "ZA", alpha3: "ZAF", numeric: "710" },
  UA: { alpha2: "UA", alpha3: "UKR", numeric: "804" },
  CR: { alpha2: "CR", alpha3: "CRI", numeric: "188" },
  UY: { alpha2: "UY", alpha3: "URY", numeric: "858" },
  VE: { alpha2: "VE", alpha3: "VEN", numeric: "862" },
  SV: { alpha2: "SV", alpha3: "SLV", numeric: "222" },
  EE: { alpha2: "EE", alpha3: "EST", numeric: "233" },
  LV: { alpha2: "LV", alpha3: "LVA", numeric: "428" },
  IS: { alpha2: "IS", alpha3: "ISL", numeric: "352" },
  MT: { alpha2: "MT", alpha3: "MLT", numeric: "470" },
  MU: { alpha2: "MU", alpha3: "MUS", numeric: "480" },
  NC: { alpha2: "NC", alpha3: "NCL", numeric: "540" },
};

export function isoOf(alpha2: string): IsoCodes {
  return ISO_BY_ALPHA2[alpha2] ?? { alpha2, alpha3: alpha2, numeric: "" };
}

export function formatIsoLine(alpha2: string): string {
  const iso = isoOf(alpha2);
  return iso.numeric ? `${iso.alpha2} · ${iso.alpha3} · ${iso.numeric}` : iso.alpha2;
}
