/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ApiOfficeTrafficRouteImport } from './routes/api/office/traffic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOfficeTrafficRoute = ApiOfficeTrafficRouteImport.update({
  id: '/api/office/traffic',
  path: '/api/office/traffic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/office': typeof OfficeRoute
  '/scan': typeof ScanRoute
  '/api/office/traffic': typeof ApiOfficeTrafficRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/office': typeof OfficeRoute
  '/scan': typeof ScanRoute
  '/api/office/traffic': typeof ApiOfficeTrafficRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/office': typeof OfficeRoute
  '/scan': typeof ScanRoute
  '/api/office/traffic': typeof ApiOfficeTrafficRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/accessibility' | '/office' | '/scan' | '/api/office/traffic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accessibility' | '/office' | '/scan' | '/api/office/traffic'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/office'
    | '/scan'
    | '/api/office/traffic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  OfficeRoute: typeof OfficeRoute
  ScanRoute: typeof ScanRoute
  ApiOfficeTrafficRoute: typeof ApiOfficeTrafficRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/office/traffic': {
      id: '/api/office/traffic'
      path: '/api/office/traffic'
      fullPath: '/api/office/traffic'
      preLoaderRoute: typeof ApiOfficeTrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  OfficeRoute: OfficeRoute,
  ScanRoute: ScanRoute,
  ApiOfficeTrafficRoute: ApiOfficeTrafficRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
